# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# For help on this file's format, see https://kitchen.ci/
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /lib/systemd/systemd

platforms:
   ## SALT `2019.2`
  - name: debian-10-2019-2-py3
    driver:
      image: netmanagers/salt-2019.2-py3:debian-10
  - name: debian-9-2019-2-py3
    driver:
      image: netmanagers/salt-2019.2-py3:debian-9
  - name: ubuntu-1804-2019-2-py3
    driver:
      image: netmanagers/salt-2019.2-py3:ubuntu-18.04

provisioner:
  name: salt_solo
  log_level: debug
  salt_install: none
  require_chef: false
  data_path: test/shared
  is_file_root: true
  pillars-from-files:
    apt.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - apt

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - apt.repositories
            - apt.update
            - apt.unattended
            - apt.preferences
